### ISSUE TITLE
Alinear los elementos de la navbar en desktop

### ISSUE THREAD

**Issue by flvanney** [flvanney/ScrollWeb#3]
Quedan re rancio los botones ahi pegados arriba. Como se centra un elemento de manera vertical?

**Comment by flvanney** [comment]
![Captura de pantalla de 2020-08-20 18-00-06](https://user-images.githubusercontent.com/49128594/90825554-77137580-e30f-11ea-89ad-02609c4f1a97.png)

**Comment by lucho-sosa** [comment]
https://developer.mozilla.org/es/docs/Web/CSS/align-items

usa ese item y pone el div donde esta el menu con una height de 100 vh

**Comment by flvanney** [comment]
Andan2
